[2021-12-15 04:57:43,567] {processor.py:163} INFO - Started process (PID=63785) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:57:43,568] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 04:57:43,568] {logging_mixin.py:109} INFO - [2021-12-15 04:57:43,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:57:43,577] {logging_mixin.py:109} INFO - [2021-12-15 04:57:43,576] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:57:43,587] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:57:43,602] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.037 seconds
[2021-12-15 04:58:18,585] {processor.py:163} INFO - Started process (PID=64145) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:18,586] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 04:58:18,586] {logging_mixin.py:109} INFO - [2021-12-15 04:58:18,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:18,595] {logging_mixin.py:109} INFO - [2021-12-15 04:58:18,594] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:58:18,605] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:18,613] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-12-15 04:58:51,387] {processor.py:163} INFO - Started process (PID=64319) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:51,387] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 04:58:51,387] {logging_mixin.py:109} INFO - [2021-12-15 04:58:51,387] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:51,396] {logging_mixin.py:109} INFO - [2021-12-15 04:58:51,395] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:58:51,406] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 04:58:51,413] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-12-15 05:04:14,191] {processor.py:163} INFO - Started process (PID=824) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:14,192] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:04:14,192] {logging_mixin.py:109} INFO - [2021-12-15 05:04:14,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:14,201] {logging_mixin.py:109} INFO - [2021-12-15 05:04:14,200] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:04:14,210] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:14,218] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-12-15 05:04:49,209] {processor.py:163} INFO - Started process (PID=1028) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:49,210] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:04:49,210] {logging_mixin.py:109} INFO - [2021-12-15 05:04:49,210] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:49,219] {logging_mixin.py:109} INFO - [2021-12-15 05:04:49,218] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:04:49,229] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:04:49,237] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-12-15 05:05:21,876] {processor.py:163} INFO - Started process (PID=1246) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:21,876] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:05:21,877] {logging_mixin.py:109} INFO - [2021-12-15 05:05:21,877] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:21,886] {logging_mixin.py:109} INFO - [2021-12-15 05:05:21,885] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:05:21,896] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:21,903] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-12-15 05:05:56,451] {processor.py:163} INFO - Started process (PID=1435) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:56,452] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:05:56,453] {logging_mixin.py:109} INFO - [2021-12-15 05:05:56,453] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:56,461] {logging_mixin.py:109} INFO - [2021-12-15 05:05:56,460] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:05:56,470] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:05:56,477] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.029 seconds
[2021-12-15 05:06:28,158] {processor.py:163} INFO - Started process (PID=1549) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:06:28,158] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:06:28,159] {logging_mixin.py:109} INFO - [2021-12-15 05:06:28,158] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:06:28,167] {logging_mixin.py:109} INFO - [2021-12-15 05:06:28,166] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:06:28,178] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:06:28,186] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-12-15 05:07:02,462] {processor.py:163} INFO - Started process (PID=1681) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:02,462] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:07:02,463] {logging_mixin.py:109} INFO - [2021-12-15 05:07:02,463] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:02,472] {logging_mixin.py:109} INFO - [2021-12-15 05:07:02,471] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:07:02,481] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:02,489] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-12-15 05:07:33,917] {processor.py:163} INFO - Started process (PID=1760) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:33,917] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:07:33,918] {logging_mixin.py:109} INFO - [2021-12-15 05:07:33,918] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:33,927] {logging_mixin.py:109} INFO - [2021-12-15 05:07:33,926] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:07:33,937] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:07:33,945] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-12-15 05:08:07,063] {processor.py:163} INFO - Started process (PID=1840) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:07,064] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:08:07,064] {logging_mixin.py:109} INFO - [2021-12-15 05:08:07,064] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:07,074] {logging_mixin.py:109} INFO - [2021-12-15 05:08:07,072] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:08:07,084] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:07,091] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-12-15 05:08:39,172] {processor.py:163} INFO - Started process (PID=1942) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:39,173] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:08:39,173] {logging_mixin.py:109} INFO - [2021-12-15 05:08:39,173] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:39,182] {logging_mixin.py:109} INFO - [2021-12-15 05:08:39,180] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:08:39,191] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:08:39,200] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-12-15 05:09:15,791] {processor.py:163} INFO - Started process (PID=2092) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:15,803] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:09:15,803] {logging_mixin.py:109} INFO - [2021-12-15 05:09:15,803] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:15,812] {logging_mixin.py:109} INFO - [2021-12-15 05:09:15,811] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:09:15,822] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:15,830] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.042 seconds
[2021-12-15 05:09:48,594] {processor.py:163} INFO - Started process (PID=2296) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:48,595] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:09:48,595] {logging_mixin.py:109} INFO - [2021-12-15 05:09:48,595] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:48,617] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:09:48,621] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:09:49,149] {logging_mixin.py:109} INFO - [2021-12-15 05:09:49,149] {manager.py:496} INFO - Created Permission View: can edit on DAG:example_python_operator
[2021-12-15 05:09:49,158] {logging_mixin.py:109} INFO - [2021-12-15 05:09:49,158] {manager.py:496} INFO - Created Permission View: can read on DAG:example_python_operator
[2021-12-15 05:09:49,158] {logging_mixin.py:109} INFO - [2021-12-15 05:09:49,158] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:09:49,164] {logging_mixin.py:109} INFO - [2021-12-15 05:09:49,164] {dag.py:2408} INFO - Creating ORM DAG for example_python_operator
[2021-12-15 05:09:49,168] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:09:49,172] {logging_mixin.py:109} INFO - [2021-12-15 05:09:49,172] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:09:49,189] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.597 seconds
[2021-12-15 05:10:26,477] {processor.py:163} INFO - Started process (PID=2457) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:10:26,478] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:10:26,479] {logging_mixin.py:109} INFO - [2021-12-15 05:10:26,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:10:26,502] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:10:26,507] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:26,515] {logging_mixin.py:109} INFO - [2021-12-15 05:10:26,515] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:10:26,525] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:26,530] {logging_mixin.py:109} INFO - [2021-12-15 05:10:26,530] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:10:26,541] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.067 seconds
[2021-12-15 05:11:03,990] {processor.py:163} INFO - Started process (PID=2795) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:03,994] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:11:03,995] {logging_mixin.py:109} INFO - [2021-12-15 05:11:03,995] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:04,015] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:04,020] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:04,027] {logging_mixin.py:109} INFO - [2021-12-15 05:11:04,027] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:11:04,036] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:04,041] {logging_mixin.py:109} INFO - [2021-12-15 05:11:04,041] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:11:04,052] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.065 seconds
[2021-12-15 05:11:36,764] {processor.py:163} INFO - Started process (PID=2939) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:36,766] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:11:36,766] {logging_mixin.py:109} INFO - [2021-12-15 05:11:36,766] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:36,787] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:11:36,792] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:36,800] {logging_mixin.py:109} INFO - [2021-12-15 05:11:36,799] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:11:36,809] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:36,814] {logging_mixin.py:109} INFO - [2021-12-15 05:11:36,814] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:11:36,824] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.063 seconds
[2021-12-15 05:12:13,061] {processor.py:163} INFO - Started process (PID=3053) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:13,063] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:12:13,063] {logging_mixin.py:109} INFO - [2021-12-15 05:12:13,063] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:13,084] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:13,088] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:13,096] {logging_mixin.py:109} INFO - [2021-12-15 05:12:13,096] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:12:13,106] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:13,110] {logging_mixin.py:109} INFO - [2021-12-15 05:12:13,110] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:12:13,121] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.063 seconds
[2021-12-15 05:12:47,120] {processor.py:163} INFO - Started process (PID=3232) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:47,120] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:12:47,121] {logging_mixin.py:109} INFO - [2021-12-15 05:12:47,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:47,141] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:12:47,146] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:47,153] {logging_mixin.py:109} INFO - [2021-12-15 05:12:47,153] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:12:47,163] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:47,168] {logging_mixin.py:109} INFO - [2021-12-15 05:12:47,168] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:12:47,178] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.061 seconds
[2021-12-15 05:13:20,576] {processor.py:163} INFO - Started process (PID=3329) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:20,577] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:13:20,578] {logging_mixin.py:109} INFO - [2021-12-15 05:13:20,578] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:20,598] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:20,603] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:20,610] {logging_mixin.py:109} INFO - [2021-12-15 05:13:20,610] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:13:20,620] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:20,625] {logging_mixin.py:109} INFO - [2021-12-15 05:13:20,625] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:13:20,636] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.063 seconds
[2021-12-15 05:13:53,525] {processor.py:163} INFO - Started process (PID=3463) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:53,526] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:13:53,526] {logging_mixin.py:109} INFO - [2021-12-15 05:13:53,526] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:53,547] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:13:53,551] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:53,559] {logging_mixin.py:109} INFO - [2021-12-15 05:13:53,559] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:13:53,569] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:53,573] {logging_mixin.py:109} INFO - [2021-12-15 05:13:53,573] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:13:53,588] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.066 seconds
[2021-12-15 05:14:24,960] {processor.py:163} INFO - Started process (PID=3650) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:14:24,961] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-12-15 05:14:24,962] {logging_mixin.py:109} INFO - [2021-12-15 05:14:24,961] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:14:24,983] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-12-15 05:14:24,988] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:24,995] {logging_mixin.py:109} INFO - [2021-12-15 05:14:24,995] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:14:25,005] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:25,009] {logging_mixin.py:109} INFO - [2021-12-15 05:14:25,009] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2021-12-15 05:14:25,020] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.063 seconds
