[2021-12-15 04:57:47,353] {processor.py:163} INFO - Started process (PID=63815) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:57:47,353] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 04:57:47,354] {logging_mixin.py:109} INFO - [2021-12-15 04:57:47,354] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:57:47,365] {logging_mixin.py:109} INFO - [2021-12-15 04:57:47,363] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:57:47,375] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:57:47,383] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.033 seconds
[2021-12-15 04:58:23,161] {processor.py:163} INFO - Started process (PID=64163) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:23,162] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 04:58:23,163] {logging_mixin.py:109} INFO - [2021-12-15 04:58:23,163] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:23,173] {logging_mixin.py:109} INFO - [2021-12-15 04:58:23,172] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:58:23,183] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:23,193] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.035 seconds
[2021-12-15 04:58:55,178] {processor.py:163} INFO - Started process (PID=64342) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:55,179] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 04:58:55,179] {logging_mixin.py:109} INFO - [2021-12-15 04:58:55,179] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:55,189] {logging_mixin.py:109} INFO - [2021-12-15 04:58:55,188] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 04:58:55,200] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 04:58:55,207] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.033 seconds
[2021-12-15 05:04:17,978] {processor.py:163} INFO - Started process (PID=848) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:17,979] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:04:17,979] {logging_mixin.py:109} INFO - [2021-12-15 05:04:17,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:17,990] {logging_mixin.py:109} INFO - [2021-12-15 05:04:17,988] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:04:18,001] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:18,008] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.033 seconds
[2021-12-15 05:04:53,781] {processor.py:163} INFO - Started process (PID=1045) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:53,782] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:04:53,782] {logging_mixin.py:109} INFO - [2021-12-15 05:04:53,782] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:53,793] {logging_mixin.py:109} INFO - [2021-12-15 05:04:53,791] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:04:53,802] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:04:53,809] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:05:28,179] {processor.py:163} INFO - Started process (PID=1313) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:05:28,180] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:05:28,181] {logging_mixin.py:109} INFO - [2021-12-15 05:05:28,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:05:28,192] {logging_mixin.py:109} INFO - [2021-12-15 05:05:28,190] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:05:28,203] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:05:28,212] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.036 seconds
[2021-12-15 05:06:01,574] {processor.py:163} INFO - Started process (PID=1454) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:01,575] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:06:01,575] {logging_mixin.py:109} INFO - [2021-12-15 05:06:01,575] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:01,586] {logging_mixin.py:109} INFO - [2021-12-15 05:06:01,584] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:06:01,596] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:01,603] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.031 seconds
[2021-12-15 05:06:35,600] {processor.py:163} INFO - Started process (PID=1593) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:35,601] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:06:35,602] {logging_mixin.py:109} INFO - [2021-12-15 05:06:35,602] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:35,612] {logging_mixin.py:109} INFO - [2021-12-15 05:06:35,611] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:06:35,622] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:06:35,629] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:07:09,076] {processor.py:163} INFO - Started process (PID=1696) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:09,076] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:07:09,077] {logging_mixin.py:109} INFO - [2021-12-15 05:07:09,077] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:09,087] {logging_mixin.py:109} INFO - [2021-12-15 05:07:09,085] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:07:09,097] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:09,105] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:07:43,376] {processor.py:163} INFO - Started process (PID=1781) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:43,377] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:07:43,377] {logging_mixin.py:109} INFO - [2021-12-15 05:07:43,377] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:43,388] {logging_mixin.py:109} INFO - [2021-12-15 05:07:43,386] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:07:43,397] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:07:43,404] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:08:17,363] {processor.py:163} INFO - Started process (PID=1865) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:17,364] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:08:17,364] {logging_mixin.py:109} INFO - [2021-12-15 05:08:17,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:17,374] {logging_mixin.py:109} INFO - [2021-12-15 05:08:17,373] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:08:17,384] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:17,394] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.034 seconds
[2021-12-15 05:08:49,475] {processor.py:163} INFO - Started process (PID=1967) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:49,476] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:08:49,476] {logging_mixin.py:109} INFO - [2021-12-15 05:08:49,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:49,487] {logging_mixin.py:109} INFO - [2021-12-15 05:08:49,485] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:08:49,496] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:08:49,504] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:09:23,241] {processor.py:163} INFO - Started process (PID=2128) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:23,242] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:09:23,243] {logging_mixin.py:109} INFO - [2021-12-15 05:09:23,243] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:23,253] {logging_mixin.py:109} INFO - [2021-12-15 05:09:23,252] {dagbag.py:334} ERROR - Failed to import: /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-12-15 05:09:23,263] {processor.py:634} WARNING - No viable dags retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:23,271] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.032 seconds
[2021-12-15 05:09:58,170] {processor.py:163} INFO - Started process (PID=2341) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:58,171] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:09:58,171] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,171] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:58,194] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:09:58,199] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:09:58,712] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,712] {manager.py:496} INFO - Created Permission View: can edit on DAG:tutorial_taskflow_api_etl_virtualenv
[2021-12-15 05:09:58,721] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,720] {manager.py:496} INFO - Created Permission View: can read on DAG:tutorial_taskflow_api_etl_virtualenv
[2021-12-15 05:09:58,721] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,721] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:09:58,727] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,727] {dag.py:2408} INFO - Creating ORM DAG for tutorial_taskflow_api_etl_virtualenv
[2021-12-15 05:09:58,730] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:09:58,734] {logging_mixin.py:109} INFO - [2021-12-15 05:09:58,734] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:09:58,750] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.584 seconds
[2021-12-15 05:10:37,711] {processor.py:163} INFO - Started process (PID=2573) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:10:37,712] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:10:37,713] {logging_mixin.py:109} INFO - [2021-12-15 05:10:37,713] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:10:37,737] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:10:37,743] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:38,004] {logging_mixin.py:109} INFO - [2021-12-15 05:10:38,004] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:10:38,014] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:10:38,019] {logging_mixin.py:109} INFO - [2021-12-15 05:10:38,019] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:10:38,031] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.322 seconds
[2021-12-15 05:11:11,996] {processor.py:163} INFO - Started process (PID=2877) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:11,997] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:11:11,998] {logging_mixin.py:109} INFO - [2021-12-15 05:11:11,998] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:12,021] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:12,025] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:12,284] {logging_mixin.py:109} INFO - [2021-12-15 05:11:12,283] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:11:12,292] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:12,296] {logging_mixin.py:109} INFO - [2021-12-15 05:11:12,296] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:11:12,309] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.315 seconds
[2021-12-15 05:11:45,849] {processor.py:163} INFO - Started process (PID=2960) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:45,850] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:11:45,850] {logging_mixin.py:109} INFO - [2021-12-15 05:11:45,850] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:45,874] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:11:45,878] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:46,127] {logging_mixin.py:109} INFO - [2021-12-15 05:11:46,127] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:11:46,135] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:11:46,139] {logging_mixin.py:109} INFO - [2021-12-15 05:11:46,139] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:11:46,151] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.305 seconds
[2021-12-15 05:12:19,348] {processor.py:163} INFO - Started process (PID=3075) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:19,348] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:12:19,349] {logging_mixin.py:109} INFO - [2021-12-15 05:12:19,349] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:19,373] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:19,377] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:19,636] {logging_mixin.py:109} INFO - [2021-12-15 05:12:19,636] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:12:19,644] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:19,649] {logging_mixin.py:109} INFO - [2021-12-15 05:12:19,648] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:12:19,660] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.316 seconds
[2021-12-15 05:12:51,121] {processor.py:163} INFO - Started process (PID=3249) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:51,122] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:12:51,122] {logging_mixin.py:109} INFO - [2021-12-15 05:12:51,122] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:51,147] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:12:51,151] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:51,427] {logging_mixin.py:109} INFO - [2021-12-15 05:12:51,426] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:12:51,435] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:12:51,439] {logging_mixin.py:109} INFO - [2021-12-15 05:12:51,439] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:12:51,451] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.334 seconds
[2021-12-15 05:13:27,185] {processor.py:163} INFO - Started process (PID=3362) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:13:27,186] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:13:27,186] {logging_mixin.py:109} INFO - [2021-12-15 05:13:27,186] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:13:27,208] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:13:27,212] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:27,468] {logging_mixin.py:109} INFO - [2021-12-15 05:13:27,468] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:13:27,476] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:13:27,480] {logging_mixin.py:109} INFO - [2021-12-15 05:13:27,480] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:13:27,492] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.310 seconds
[2021-12-15 05:14:00,397] {processor.py:163} INFO - Started process (PID=3491) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:00,398] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:14:00,398] {logging_mixin.py:109} INFO - [2021-12-15 05:14:00,398] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:00,423] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:00,429] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:00,685] {logging_mixin.py:109} INFO - [2021-12-15 05:14:00,685] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:14:00,694] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:00,698] {logging_mixin.py:109} INFO - [2021-12-15 05:14:00,698] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:14:00,709] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.315 seconds
[2021-12-15 05:14:36,426] {processor.py:163} INFO - Started process (PID=3727) to work on /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:36,427] {processor.py:620} INFO - Processing file /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-12-15 05:14:36,428] {logging_mixin.py:109} INFO - [2021-12-15 05:14:36,428] {dagbag.py:500} INFO - Filling up the DagBag from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:36,451] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-12-15 05:14:36,456] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:36,739] {logging_mixin.py:109} INFO - [2021-12-15 05:14:36,739] {dag.py:2389} INFO - Sync 1 DAGs
[2021-12-15 05:14:36,748] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2021-12-15 05:14:36,752] {logging_mixin.py:109} INFO - [2021-12-15 05:14:36,752] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2021-12-15 05:14:36,764] {processor.py:171} INFO - Processing /opt/conda/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.340 seconds
